### ISSUE TITLE
Release Definition failing

### ISSUE THREAD

**Issue by luije87** [almbox/vsts-ssis-extension#1]
Hi everyone,

I am using visual studio online and I am using SSIS Deploy task from build definition, the package is deployed to SQL servers but when I tried to use the task from Release definition, where should be, I am getting this error:

Task_InternalError Exception calling ".ctor" with "1" argument(s): "Failed to connect to server ."

The configuration is exactly the same, for some reason is failing.

**Comment by schwaizi** [comment]
Hi Luis, apparently i found the same issue reported on stackoverflow

https://stackoverflow.com/questions/45978672/build-and-deploy-ssis-packages-using-vsts

The release agent service account must have permission on the target SQL Server as it is used for Windows Authentification. And of course access.

Can you check that please? Can you see any event in the SQL log?

**Comment by luije87** [comment]
Looks like the task is not reading my connection string, the error message is, in the [link](https://stackoverflow.com/questions/45978672/build-and-deploy-ssis-packages-using-vsts) shows **SQL connection String** is populated. I am using same agent for build and release.

SQL Connection String: 
Task_InternalError Exception calling ".ctor" with "1" argument(s): "**Failed to connect to server** ."

**Comment by schwaizi** [comment]
Hi Luis,
the Build and Release use the same task (same code).
Did you check the SQL Logs? Can you see any event?
Can you set system.debug to true and post your log please?

**Comment by luije87** [comment]
Hi @schwaizi ,

Problem solved, but I think could be a bug, I changed in release definition:

Integrated Security parameter to : Custom connection String
Connection String: Data Source=SQLSERVER;Initial Catalog=master;Integrated Security=SSPI;

Before I did not see any sql logs related. I will run the failed task again and post my log.

I appreciate you help

**Comment by schwaizi** [comment]
Very good Luis,

So you saying your Task is Build Def. and Release Def. are configured exactly the same? Can you check there no spaces in the Servername, etc?

The Task variable is:
$sqlConnectionString = "Data Source=$ServerName;Initial Catalog=master;Integrated Security=SSPI;"

So it should be fine.
I may implement $ServerName.Trim() to make sure there is no spaces in the servername to be sure. But other than that i have no other idea where the problem can be, especially when it is running in Build.

**Comment by luije87** [comment]
@schwaizi I am sorry ,I can reproduce the problem anymore, now is working perfectly with Integrated Security SSPI (Windows Authentication). Weird scenario, thanks for your time and help.

**Comment by schwaizi** [comment]
@luije87 sounds good to me! Thanks for the info and have fun with VSTS!
