### ISSUE TITLE
TFS does not "see" the new version of this add-on

### ISSUE THREAD

**Issue by ewithersict** [almbox/vsts-ssis-extension#3]
We have installed the latest version of the SSIS Build extension but our TFS server does not recognize that it is installed. It only sees the older version that does not support SSDT 2017. Could you please advise the best way to upgrade? We have a large number of builds utilizing the "old" version and I'm hoping there is an upgrade option rather than uninstall/reinstall option that would cause us to have to modify all of our existing builds. 
We are on Version 15.105.25910.0 of TFS.

**Comment by schwaizi** [comment]
Hi, the extension should be available for 2017 and later TFS Version.
I've updated targets in the extension with "2017 and later" according to Microsoft docu instead of specifying the versions directly. Please give a try.

`
    "targets": [
        {
            "id": "Microsoft.VisualStudio.Services.Cloud"
        },
        {
            "id": "Microsoft.TeamFoundation.Server",
            "version": "[15.0,)"
        }
    ],
`

**Comment by schwaizi** [comment]
@ewithersict are you able to update the updated extension on your TFS?

**Comment by RepeatDaily** [comment]
@schwaizi I also have experienced an issue installing this extension to TFS 2017.  We're on TFS 15.112.26307.0.

Installing from the marketplace I get an error, 
    "**Something went wrong while downloading the extension**."  

When I tried to install the vsix directly I get the error
    **"Extension package contains invalid characters(8,45) Error: XML Document- 'Free' is not a valid value for global::Microsoft.VisualStudio.Services.Gallery.WebApi.PublishedExtensionFlags."**
