### ISSUE TITLE
Unable to build VS2017 project

### ISSUE THREAD

**Issue by Mortimer452** [almbox/vsts-ssis-extension#4]
Updated the SSIS Build & Deploy task, installed Visual Studio 2017 and latest SSDT on the build server, but under the "Advanced" section for Devenv version I only see 12 and 14, there is no option to choose 15 (VStudio 2017 version)

**Comment by schwaizi** [comment]
Hi, just a quick question. When editing the Task, can you see version 1.x or is it 0.x ?

https://docs.microsoft.com/en-us/vsts/build-release/concepts/process/tasks?view=vsts#task-versions

**Comment by Mortimer452** [comment]
Editing the task showed version 0.x.  I tried changing it to v1.x and got several new options, including updated Devenv version for VS2017.  Thanks for the help!  Closing this out now.

**Comment by schwaizi** [comment]
Nice! Happy to support.
