### ISSUE TITLE
Extension will not install to TFS 2017 from Marketplace, or Manually using the VSIX

### ISSUE THREAD

**Issue by RepeatDaily** [almbox/vsts-ssis-extension#5]
I have experienced an issue installing this extension to TFS 2017. We're on TFS 15.112.26307.0.

Installing from the marketplace I get an error,
"Something went wrong while downloading the extension."

When I tried to install the vsix directly I get the error
"Extension package contains invalid characters(8,45) Error: XML Document- 'Free' is not a valid value for global::Microsoft.VisualStudio.Services.Gallery.WebApi.PublishedExtensionFlags."

**Comment by schwaizi** [comment]
Hi @RepeatDaily, thanks for pointing out this issue.

I changed galleryFlags to "Public" accosrding to MS Docs
(instead of "Free" which was probably typo mistake)

`
{
    "galleryFlags": [
        "Public"
    ]
} 
`

**Comment by RepeatDaily** [comment]
Hello @schwaizi.  Thanks for responding.  

I now get the following error when attempting the install. 

![image](https://user-images.githubusercontent.com/38541849/39139567-408451be-46f0-11e8-84d4-5ce3afda5e33.png)

**Comment by RepeatDaily** [comment]
@schwaizi  This is a first install - I did not see it on the list of installed extensions **before** attempting the install this time around, however, now I **do** see it as installed with an error, and I have asked my TFS administrator to remove it so that it can be re-attempted.  I only have the ability to manage my own TFS collection, not the whole server.

**Comment by schwaizi** [comment]
The current status seems to be correct. The first installation with the bug failed and it need to be deleted.
I was just wondering why it failed for you, because of the Extension have more than 100 downloads without this issue. Seems like it affected first install only, but can not confirm it.

**Comment by RepeatDaily** [comment]
@schwaizi as soon as I hear back from my TFS admin/owner I'll re-attempt the install.  They may be able to see more than I can upon investigation; all I get is the "friendly" error in the UI.

**Comment by RepeatDaily** [comment]
@schwaizi OK the extension has been removed.  Before I attempt to install again, can you tell me if this extension requires "server level" permissions, or should I be able to install this directly to my TFS collection?

**Comment by schwaizi** [comment]
@RepeatDaily 

Hi, i updated build config which changed task.json files version. Can you give a try please?

Are you planning upgrade of your system to Update 2 or higher? I can provide to you extension with single task which may be solution for you, but for one time only and without future updates.

**Comment by RepeatDaily** [comment]
@schwaizi Thanks for the response.  My TFS admin did say that they're planning an upgrade, but didn't give a timeline.  

I'll give the update a try today, and report back.  Thank you for the support.

**Comment by RepeatDaily** [comment]
@schwaizi unfortunately, the extension still returns a tasks.json error on install.  We'll just have to wait until we can install update 2.  Thanks for looking into this.  If possible I would recommend setting the extension in the marketplace so that it's clear that it requires update 2 - I suspect others will have this problem.
