### ISSUE TITLE
Getting internal error.

### ISSUE THREAD

**Issue by AstridMalanka** [almbox/vsts-ssis-extension#6]
I don't know if it my lack of understanding, but I did follow the steps and I keep getting the same error on the build. "Internal Error: Microsoft.PowerShell.Commands.WriteErrorException Devenv.com in C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Devenv.com not found"

I am using visual studio 2017 professional. 

I check and the location is correct and the file is there. I am not sure exactly where it is looking for it. because it is not in my computer.

i did run it from powershell and the command worked.

**Comment by schwaizi** [comment]
Hi, can tou be more specific please? How your setup is looks like. Is The devenv placed on the machine where the agent is running? I can not identify those information frim the error message.

**Comment by schwaizi** [comment]
Hi, you can chose Private Agent or Hosted Agent. both should work. Which option are you using?

You mentioned the "devenv.com is there". Do You mean it is on your computer or on computer hosting your Private Agent or on Hosted Agent?

Those are the essential information to be able to look closely where the error come from.

**Comment by schwaizi** [comment]
Hosted Agent 2017 have Visual Studio 2017 Enterprise installed so you need to choose this version.

Please note the build is running on the Hosted Agent (in the cloud) which means it have nothing to do with your devenv.com installed on your local computer you refering to.

Hope that’s help to understand how it works.

**Comment by AstridMalanka** [comment]
So I need to choose which version? I am sorry, I didn't get that.

**Comment by schwaizi** [comment]
Enterprise version

**Comment by AstridMalanka** [comment]
I am not able to use the enterprise version, as the company doesn't have it, but from what it says on the Microsoft site, the agent should work also on the professional license.
https://www.visualstudio.com/license-terms/mlt553423/

It does work on my other builds which are done with the same visual studio.

**Comment by schwaizi** [comment]
Hi, those Agents mentioned in the licensing are on-premise versions. In VSTS you paying for build minutes or using free minutes. That’s my understanding but i’m not licensing expert.

You need to look in inventory of installed sofware on Hosted Agent 2017

https://github.com/Microsoft/vsts-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md

And i see Enterprise version only as installed.

If you want to use Professional version then you would need to build own Server with the specific version. Or just install VSTS agent on your computer and link it with the VSTS for testing purposes.

That’s my advice on possible options.

**Comment by schwaizi** [comment]
I have no information about your other builds. You saying they are not SSIS builds and i assume they not using devenv.com.

As far i can see the problem is in the VS Version you selected in the Extension for Hosted Agent 2017.

**In the Drop Down Menu you need to select: Hosted VS2017**
(Not the professional version installed on your computer)

Can you confirm the output then please?

**Comment by AstridMalanka** [comment]
The error comes after the ssis task is called, not before.
The problem comes from the devenv version chosen on the drop down of the ssis task, that is where it says professional. 
And yes, on the drop up menu I do use hosted vs2017

2018-04-24T20:23:05.2094384Z ##[section]Starting: Build SSIS 
2018-04-24T20:23:05.2321471Z ==============================================================================
2018-04-24T20:23:05.2321656Z Task         : SSIS Build
2018-04-24T20:23:05.2321829Z Description  : Build SQL Server Integration Services Project into .ispac file using legacy Package Deployment Model
2018-04-24T20:23:05.2321999Z Version      : 1.0.1143
2018-04-24T20:23:05.2322120Z Author       : ToxicGlobe
2018-04-24T20:23:05.2322264Z Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=TG.VSTS-SSIS)
2018-04-24T20:23:05.2322437Z ==============================================================================
2018-04-24T20:23:08.8323465Z   _____        _     ___ _     _         
2018-04-24T20:23:08.8324306Z  |_   _|____ _(_)__ / __| |___| |__  ___ 
2018-04-24T20:23:08.8324624Z    | |/ _ \ \ / / _| (_ | / _ \ '_ \/ -_)
2018-04-24T20:23:08.8324851Z    |_|\___/_\_\_\__|\___|_\___/_.__/\___|
2018-04-24T20:23:08.8325074Z                                          
2018-04-24T20:23:08.8325364Z ==============================================================================
2018-04-24T20:23:08.8325803Z Starting BuildSSISTask
2018-04-24T20:23:08.8640503Z ==============================================================================
2018-04-24T20:23:08.8661901Z Devenv version: VS2017prof
2018-04-24T20:23:09.2828740Z 
2018-04-24T20:23:09.6259982Z ##[error]Internal Error: Microsoft.PowerShell.Commands.WriteErrorException Devenv.com in C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Devenv.com not found
2018-04-24T20:23:09.6653295Z ##[section]Finishing: Build SSIS

**Comment by schwaizi** [comment]
Hi,
can you double check it please?

This is drop down meny config in the Extension

```
                "VS2013": "VS2013",
                "VS2015": "VS2015",
                "VS2017ent": "VS2017 Enterprise",
                "VS2017prof": "VS2017 Professional",
                "VS2017comm": "VS2017 Community",
                "VS2017new": "VS2017 New Instance",
                "hostedVS2017": "Hosted VS2017",
                "custom": "Custom"
```

And this is Switch in the Script

```
		VS2013       {$compiler = "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Devenv.com"} 
		VS2015       {$compiler = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Devenv.com"}
		VS2017ent    {$compiler = "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Devenv.com"}
		VS2017prof   {$compiler = "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Devenv.com"}
		VS2017comm   {$compiler = "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Devenv.com"}
		VS2017new    {$compiler = "C:\Program Files (x86)\Microsoft Visual Studio\2017\SQL\Common7\IDE\Devenv.com"}
		hostedVS2017 {$compiler = "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Devenv.com"}
		Custom       {$compiler = $denevPath}
```

I would suggest you will change the version to custom and then back to Hosted VS 2017 and save it.

**Comment by AstridMalanka** [comment]
I think we are getting mixed up.
On the phase 1 which runs on an agent - i am using hosted vs2017 that comes with vsts. - same as in every other built I have and i don't get errors there.

On the build ssis task with the the conf you are showing me, i am using vs2017 professional (from the drop down menu).
I have also tried but it is showing me the path in my solution, not in my computer. and the devenv file is not on my solution, but on my computer.

**Comment by AstridMalanka** [comment]
maybe i don't need to run on a agent on phase 1 and just run without one?

**Comment by schwaizi** [comment]
> On the build ssis task with the the conf you are showing me, i am using vs2017 professional (from the drop down menu).

Please select "Hosted VS2017" if you run the task on Hosted Agent 2017.
This is what i asked for in https://github.com/almbox/vsts-ssis-extension/issues/6#issuecomment-384351784

If you have VSTS Agent installed on your computer, select the appropriate version of visual studio installed on your computer.

**Comment by AstridMalanka** [comment]
Hi,
I tried what you asked and it has been running for 4 minutes with the same message:
Waiting for console output from an agent...

it is still not working.

**Comment by AstridMalanka** [comment]
I don't know why you think me saying: "it is still not working" when we are clearly talking about my issue is offensive. 
anyway, thanks
i will not use the extension anymore.
will look for another solution that will work for me.

**Comment by schwaizi** [comment]
just wondering why you put 1 star in the extension review if the solution has been found and you got a plenty of free support from my side for your VSTS configuration

But thanks anyway...

**Comment by AstridMalanka** [comment]
i changed it to one start, because it became an ego issue, instead of trying to actually help.
when i told you it didn't work, you got offended, even though we are having this conversation because it didn't work on my side.
let also not forget the "So please be keep the conversation on professional level. Otherwise you always have the option to uninstall it."
and then of course deleting the comments...
a resolution has not been found... but again... you will probably delete my comment.
i do wish you the best of luck.

**Comment by schwaizi** [comment]
I agree i deleted the comments. Your comments has been unprofessional and it didn't contain any technical details about the issue you had with your VSTS configuration as mentioned in the conversation above.

Second, you put bad review on the extension where the final reason was your VSTS configuration hasn't been correct. Even so i provided you the support to be able to use the extension.

One tip.
If the build is not working, but the task is running, i would suggest you to look in the SSIS project configuration instead of  expecting me to do the job to find out how is your project configured and your infrastructure setup, etc.

**Comment by schwaizi** [comment]
btw, it is not about my ego. It is about spending my time in reading non-productive comments "it doesn't work". But importantly it is about your incompetence to configure basic settings and your incompetence to answer/do what you been asked for and not even able to say single thank you. To be honest, your communication has been pretty annoying..
