### ISSUE TITLE
Spelling mistake in Deploy Task Integrated Security input

### ISSUE THREAD

**Issue by MDendura** [almbox/vsts-ssis-extension#9]
Only a minor spelling mistake. No code in this repo or I'd submit a PR.

"Authentification" => "Authentication"

See the following:

![image](https://user-images.githubusercontent.com/917692/39991963-233bbeec-5769-11e8-83ca-ec915cc4a25b.png)

**Comment by schwaizi** [comment]
many thanks! new version is available in marketplace
